### ISSUE TITLE
Any plans for a Swift SDK

### ISSUE THREAD

**Issue by sbo-nemlig** [queueit/ios-webui-sdk#15]
Hey do you have any plans for a Swift version of the SDK, or making the code open source so others can do it ?

**Comment by frwiqueueit** [comment]
Hi. No, we have no plans for a Swift version of the SDK. In regards to the open source version would you or others be interested in converting our existing objective-c solution to Swift? We can be standby to help support this endeavor.

**Comment by sbo-nemlig** [comment]
It could be a option.
