### ISSUE TITLE
Missing Nullability Type Specifiers

### ISSUE THREAD

**Issue by Jake-Prickett** [queueit/ios-webui-sdk#16]
We recently integrated Queue-It into our project using the `.xcframework` approach and noticed some warnings being emitted from the library around providing nullability specifiers in `QueueItEngine.h`. 

Would it be possible to have these added in to avoid generating warnings in consuming applications?

I've listed the specific methods below for your reference:

```objective-c
// QueueItEngine.h 

@property (nonatomic)id<QueuePassedDelegate> queuePassedDelegate;

-(void)handleAppEnqueueResponse:(NSString*) queueId
                       queueURL:(NSString*) queueURL
           queueURLTTLInMinutes:(int) ttl
                 eventTargetURL:(NSString*) targetURL
                   queueItToken:(NSString*) token;

@protocol QueuePassedDelegate <NSObject>
-(void)notifyYourTurn:(QueuePassedInfo*) queuePassedInfo;
@end

@protocol QueueITUnavailableDelegate <NSObject>
-(void)notifyQueueITUnavailable: (NSString *) errorMessage;
@end
```

**Comment by frwiqueueit** [comment]
Thanks Jake for bringing this to our attention. We will look into it ASAP.

**Comment by Jake-Prickett** [comment]
@frwiqueueit Any update on this one? Please let me know if I should close my open PR.

https://github.com/queueit/ios-webui-sdk/pull/17

**Comment by frwiqueueit** [comment]
Thank you. Will will get to this soon and get it merged into master.

**Comment by Jake-Prickett** [comment]
Alrighty, it's going on two weeks now - can we get an ETA on the completion of adding these nullability specifiers and a new release? 

Would you recommend we reach out to our Queue-It contact for our company? @frwiqueueit

**Comment by frwiqueueit** [comment]
Hi Jake, sorry about this. We were not aware about the urgency.
We will get a new release out today or tomorrow.

**Comment by sp0x** [comment]
Version 3.0.9 of the connector now has the nullability type annotation added.

**Comment by Jake-Prickett** [comment]
Thanks for addressing this one! Looking much better from our end.
