### ISSUE TITLE
Retain cycles and "bad" objective-c

### ISSUE THREAD

**Issue by gstrobl17** [queueit/ios-webui-sdk#19]
- This library has some retain cycles that prevent it from releasing a `QueueITEngine` instance. 
- It is missing a `super` call in the view controller. 
- And, for our implementation, I needed to know when the view controller did appear. (If an alert view is being displayed - like a prompt to enable push notifications, trying to present the QueueIT view controller will fail. The call to `raiseQueueViewWillOpen` will be made within `-[QueueITEngine showQueue:targetUrl:]`; however, the `presentViewController` will essentially fail. If the view controller is actually presented, the completion handler on the `presentViewController` will be executed. So the code should look like this:
```
-(void)showQueue:(NSString*)queueUrl targetUrl:(NSString*)targetUrl
{
    [self raiseQueueViewWillOpen];
    
    QueueITWKViewController *queueWKVC = [[QueueITWKViewController alloc] initWithHost:self.host
                                                                           queueEngine:self
                                                                              queueUrl:queueUrl
                                                                        eventTargetUrl:targetUrl
                                                                            customerId:self.customerId
                                                                               eventId:self.eventId];
    if (@available(iOS 13.0, *)) {
        [queueWKVC setModalPresentationStyle: UIModalPresentationFullScreen];
    }
    if (self.delayInterval > 0) {
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(self.delayInterval * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            [self.host presentViewController:queueWKVC animated:YES completion:^{
                self.currentWebView = queueWKVC;
                [self raiseQueueViewDidAppear];
            }];
        });
    } else {
        dispatch_async(dispatch_get_main_queue(), ^{
            [self.host presentViewController:queueWKVC animated:YES completion:^{
                self.currentWebView = queueWKVC;
                [self raiseQueueViewDidAppear];
            }];
        });
    }
}

```

I have attached all the files that I have modified for your review. (I would have created a PR but I didn't have access in your repo.)
[Archive.zip](https://github.com/queueit/ios-webui-sdk/files/7970925/Archive.zip)

**Comment by felixdrud** [comment]
@gstrobl17 I see now that we never replied to your issue.
Thank you for bringing this to our attention, we will take a look at it as soon as time permits.

**Comment by sp0x** [comment]
Version 3.0.11 takes care of this. Thanks for the archive.
