### ISSUE TITLE
Download link whitepaper

### ISSUE THREAD

**Issue by lammertw** [queueit/ios-webui-sdk#25]
One of the first things in the readme is the following:
```
Before starting please download the whitepaper Mobile App Integration from GO Queue-it Platform. This whitepaper contains the needed information to perform a successful integration.
```

Is it possible to provide a link to this whitepaper? I'm unable to find it's download location?

**Comment by Ista-Queueit** [comment]
You need to login to your Queue-it self service account https://go.queue-it.net/account/login and click on the top right corner ? and select White papers. 
![image](https://user-images.githubusercontent.com/110022999/192217250-6945588a-471a-4a45-9340-b01b9a5aa11f.png)

Direct link to Mobile integration white paper: https://support.queue-it.com/hc/en-us/articles/360014298920
