### ISSUE TITLE
Crash on tapping custom URL in Queue Page body

### ISSUE THREAD

**Issue by antonys1** [queueit/ios-webui-sdk#28]
Tapping a [custom URL](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app) in the Queue Page body crashes on the following line in the SDK:

https://github.com/queueit/ios-webui-sdk/blob/15654f03c1e2e1feb0b4f12c482ff4ae11108cef/QueueITLib/QueueITWKViewController.m#L139

This is because a custom URL e.g. `myphotoapp:albumname?index=1` doesn't have a `host` and is returning `nil` where the `containsString` method is expecting a non-nil value.

Can you update the logic for determining `isQueueUrl` that accommodates custom URLs too please?

**Comment by caddeo** [comment]
We currently don't support this, since it would alter the flow of how the WebView works.
