### ISSUE TITLE
Possible to get Swift Package Manager support added?

### ISSUE THREAD

**Issue by desai-deep** [queueit/ios-webui-sdk#29]
We are transitioning away from CocoaPods to SPM – this feels like the 'modern' way of managing 3rd party dependencies on iOS.

**Comment by caddeo** [comment]
Thanks for reaching out.

We are currently looking into extending our support for swift, but there's no immediate plans yet. 

Please reach out to your Queue-it representative if you want to discuss anything further related to your implementation.
