### ISSUE TITLE
Privacy manifest

### ISSUE THREAD

**Issue by sbo-nemlig** [queueit/ios-webui-sdk#31]
Will your SDK have a privacy manifest before Apples deadline spring 2024

https://developer.apple.com/news/?id=r1henawx

**Comment by 3520kramer** [comment]
Thanks for reaching out to us. We are currently looking into this and will get back to you by end of this week

**Comment by 3520kramer** [comment]
Hi @sbo-nemlig

I apologize for the late reply. Yes, our SDK will contain the privacy manifest. We'll add this as soon as possible

**Comment by 3520kramer** [comment]
We have now released v4.3.1 which includes the privacy manifest. We apologise for the delay on this one
