### ISSUE TITLE
publish the podspec for version 3.4.3

### ISSUE THREAD

**Issue by vachonf** [queueit/ios-webui-sdk#39]
I think you forgot to add the latest version here:
https://github.com/CocoaPods/Specs/blob/master/Specs/1/8/9/QueueITLibrary/3.4.2/QueueITLibrary.podspec.json

It's impossible to update our podfile with the latest version. 

regards, 

François Vachon.

**Comment by 3520kramer** [comment]
Sorry for the inconvenience. Our release pipeline didn't report that it failed publishing to CocoaPods. A new version has been published: https://github.com/CocoaPods/Specs/blob/master/Specs/1/8/9/QueueITLibrary/3.4.3/QueueITLibrary.podspec.json

Thanks for bringing this to our attention
