### ISSUE TITLE
Pod install does not include lib in project

### ISSUE THREAD

**Issue by andre-gomes-takealot** [queueit/ios-webui-sdk#5]
My platform target in my PODFILE is "10.0"

I've include pod 'QueueITLibrary', '~> 2.11.2' in it but the library does not get linked.

Error:
```
ld: warning: directory not found for option '-L/Users/andre.gomes/Library/Developer/Xcode/DerivedData/takealot-ghyvcodjcbiklmekzeaxfxkktgqt/Build/Products/Debug-iphonesimulator/QueueITLibrary'
ld: library not found for -lQueueITLibrary
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by thviQit** [comment]
Hi Andre

Just to begin with, are you using the `*.xcworkspace` file to open the project?

**Comment by andre-gomes-takealot** [comment]
Hi Thomas,

Yes, I was launching Xcode via the workspace and no project. However, since logging my issue, I have since resolved my issue but performing:

pod clean 
pod deintegrate
pod install

Thanks again for getting in contact.

Regards,

André Gomes
C: 0838588799 T: 087 820 5000 E: andre.gomes@takealot.com <mailto:andre.gomes@takealot.com>
7th floor, Auto Atlantic Building, 7 Hertzog Boulevard, Foreshore, Cape Town
Our company is built around the simple concept that the customer comes first.
